# Generated by Django 4.1.2 on 2022-11-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_get_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentscase',
            name='max_price',
            field=models.DecimalField(decimal_places=10, default='', max_digits=20, verbose_name='Мин цена'),
        ),
        migrations.AlterField(
            model_name='percentscase',
            name='min_price',
            field=models.DecimalField(decimal_places=10, default='', max_digits=20, verbose_name='Макс цена'),
        ),
        migrations.AlterField(
            model_name='spotcase',
            name='price',
            field=models.DecimalField(decimal_places=10, default='', max_digits=20, verbose_name='Процент'),
        ),
    ]
