# Generated by Django 4.1.2 on 2022-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_get_price', '0002_alter_percentscase_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentscase',
            name='max_price',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True, verbose_name='Мин цена'),
        ),
        migrations.AlterField(
            model_name='percentscase',
            name='min_price',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True, verbose_name='Макс цена'),
        ),
        migrations.AlterField(
            model_name='percentscase',
            name='percent',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='spotcase',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=20, null=True, verbose_name='Процент'),
        ),
    ]
