# Generated by Django 4.1.2 on 2022-11-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_get_price', '0003_alter_percentscase_max_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_name', models.CharField(default='', max_length=64, verbose_name='Тг название')),
                ('back_name', models.CharField(default='', max_length=64, verbose_name='название для программы')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
    ]
